wings-order-form/config/routes.rb
Rails.application.routes.draw do
  root "wing_orders#index"
  resources :wing_orders, only: [:index, :new, :create]
end

wings-order-form/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wings-order-form/app/models/flavor.rb
class Flavor < ApplicationRecord
  has_many :order_flavors
  has_many :wing_orders, through: :order_flavors

  validates :name, presence: true
end

wings-order-form/app/models/order_flavor.rb
class OrderFlavor < ApplicationRecord
  belongs_to :wing_order
  belongs_to :flavor

  validates :wing_order, presence: true
  validates :flavor, presence: true
end

wings-order-form/app/models/wing_order.rb
class WingOrder < ApplicationRecord
  STATES = [
    ["Massachusetts", "MA"],
    ["New Hampshire", "NH"],
    ["Connecticut", "CT"],
    ["Maine", "ME"]
  ]

  QUANTITIES = [
    [10, "10 wings"],
    [25, "25 wings"],
    [50, "50 wings"],
    [100, "100 wings"]
  ]

  has_many :order_flavors
  has_many :flavors, through: :order_flavors

  validates :customer_name, presence: true
  validates :city, presence: true
  validates :state,
    presence: true,
    inclusion: { in: STATES.map { |state| state[1] } }
  validates :quantity,
    presence: true,
    numericality: { only_integer: true },
    inclusion: { in: QUANTITIES.map { |quantity| quantity[0] } }
  validates :ranch_dressing, inclusion: { in: [true, false] }
end

wings-order-form/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wings-order-form/app/controllers/wing_orders_controller.rb
class WingOrdersController < ApplicationController
  def index
    @wing_orders = WingOrder.all
  end

  def new
    @wing_order = WingOrder.new
    @state_collection = WingOrder::STATES
    @quantity_collection = WingOrder::QUANTITIES
    @flavor_collection = Flavor.all
  end

  def create
    @wing_order = WingOrder.new(wing_order_params)
    @wing_order.flavors = Flavor.where(id: params[:wing_order][:flavor_ids])
    if @wing_order.save
      flash[:notice] = "Wing order created!"
      redirect_to wing_orders_path
    else
      flash[:alert] = "Wing order not created"
      @state_collection = WingOrder::STATES
      @quantity_collection = WingOrder::QUANTITIES
      @flavor_collection = Flavor.all
      render :new
    end
  end

  private

  def wing_order_params
    params.require(:wing_order).permit(
      :customer_name,
      :city,
      :state,
      :quantity,
      :ranch_dressing
    )
  end
end

wings-order-form/app/helpers/application_helper.rb
module ApplicationHelper
end

wings-order-form/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="columns small-12">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

wings-order-form/app/views/wing_orders/index.html.erb
<h1>Wing Orders</h1>

<div class=".wing_orders">
<%  @wing_orders.each do |wing_order| %>
  <div class=".wing_order">
    <h2><%= wing_order.customer_name %></h2>
    <span><%= "#{wing_order.city}, #{wing_order.state}" %></span>
    <span>Quantity: <%= wing_order.quantity %></span>
    <span>Include Ranch Dressing?: <%= wing_order.ranch_dressing %></span>
    <h3>Flavors To Include</h3>
    <% wing_order.flavors.each do |flavor| %>
      <span><%= flavor.name %></span>
    <% end %>
  </div>
  <hr />
<% end %>
</div>

<%= link_to "New Order", new_wing_order_path %>

wings-order-form/app/views/wing_orders/new.html.erb
<h1>New Wing Order</h1>
<form class="new_wing_order" id="new_wing_order" action="/wing_orders" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="authenticity_token" value="2PGpBg7eEvtrzp9P7+C4mGH1ieW0mg0w9c+1l1SgeK1+ra8GEg5iDkZ26nEVkjRJCkcjgmMjH5CLwdoI2d1XLA==">

  <div class="row">
    <label for="wing_order_customer_name">Full Name</label>
    <input type="text" name="wing_order[customer_name]" id="wing_order_customer_name">
  </div>

  <div class="row">
    <label for="wing_order_city">City</label>
    <input type="text" name="wing_order[city]" id="wing_order_city">
  </div>

  <div class="row">
    <label for="wing_order_state">State</label>
    <select name="wing_order[state]" id="wing_order_state">
      <% @state_collection.each do |state_array| %>
        <option value="<%= state_array.last %>"><%= state_array.first %></option>
      <% end %>
    </select>
  </div>

  <div class="row">
    <label for="wing_order_quantiy">Quantity</label>

    <% @quantity_collection.each do |quantity_array| %>
      <input type="radio" value="<%= quantity_array.first %>" name="wing_order[quantity]" id="<%= "wing_order_quantity_#{quantity_array.first}" %>">
      <label for="<%= "wing_order_quantity_#{quantity_array.first}" %>"><%= quantity_array.last %></label>
    <% end %>
  </div>

  <div class="row">
    <label for="wing_order_ranch_dressing">Add Ranch Dressing</label>
    <input name="wing_order[ranch_dressing]" type="hidden" value="0">
    <input type="checkbox" value="1" name="wing_order[ranch_dressing]" id="wing_order_ranch_dressing">
  </div>

  <div class="row">
    <label for="wing_order_flavor_ids">Flavors</label>

    <% @flavor_collection.each do |flavor| %>
      <input type="checkbox" value="<%= flavor.id %>" name="wing_order[flavor_ids][]" id="<%= "#{flavor.id}" %>">
      <label for="<%= "#{flavor.id}" %>"><%= "#{flavor.name}" %></label>
    <% end %>

    <input type="hidden" name="wing_order[flavor_ids][]" value="">
  </div>

  <div class="row">
    <input type="submit" name="commit" value="Place Order">
  </div>
</form>